{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Product API",
    "description" : "PactFlow Product API demo",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "tags" : [ {
    "name" : "product_model",
    "description" : "<SchemaDefinition schemaRef=\"#/components/schemas/Product\" />\n",
    "x-displayName" : "The Product Model"
  } ],
  "paths" : {
    "/products" : {
      "get" : {
        "summary" : "List all products",
        "description" : "Returns all products",
        "operationId" : "getAllProducts",
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json; charset=utf-8" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Product"
                  }
                },
                "examples" : {
                  "application/json" : {
                    "value" : [ {
                      "id" : "1234",
                      "type" : "food",
                      "price" : 42
                    } ]
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid ID supplied",
            "content" : { }
          }
        }
      },
      "post" : {
        "summary" : "Create a product",
        "description" : "Creates a new product",
        "operationId" : "createProduct",
        "requestBody" : {
          "description" : "Create a new Product",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Product"
              },
              "examples" : {
                "application/json" : {
                  "value" : {
                    "id" : "1234",
                    "type" : "food",
                    "price" : 42
                  }
                }
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json; charset=utf-8" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                },
                "examples" : {
                  "application/json" : {
                    "value" : {
                      "id" : "1234",
                      "type" : "food",
                      "price" : 42
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/product/{id}" : {
      "get" : {
        "summary" : "Find product by ID",
        "description" : "Returns a single product",
        "operationId" : "getProductByID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "ID of product to get",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          },
          "example" : 10
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json; charset=utf-8" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Product"
                },
                "examples" : {
                  "application/json" : {
                    "value" : {
                      "id" : "1234",
                      "type" : "food",
                      "price" : 42
                    }
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid ID supplied",
            "content" : { }
          },
          "404" : {
            "description" : "Product not found",
            "content" : { }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Product" : {
        "required" : [ "id", "name", "price" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "type" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "version" : {
            "type" : "string"
          },
          "price" : {
            "type" : "number"
          }
        },
        "additionalProperties" : false
      },
      "inline_response_200" : {
        "oneOf" : [ {
          "$ref" : "#/components/schemas/Product"
        } ]
      }
    }
  }
}